version: "3.3"

services:

  matchq-frontend:
    build: './angular-src'
    ports:
      - "4200:4200"
      - "49153:49153"
    networks:
      - backend
    depends_on:
      - matchq-server
    volumes:
      - ./angular-src:/home/node/client/
      - /home/node/client/node_modules

  matchq-server:
    build: './server'
    ports:
     - "8080:8080"
    networks:
     - backend
    depends_on:
     - matchq-database
    volumes:
     - ./server:/home/node/server/
     - /home/node/server/node_modules

  matchq-database:
    image: mongo:latest
    ports:
     - "27017:27017"
    networks:
     - backend

networks:
  backend: